[project]
name = "sms-freiburg"
dynamic = ["version"]
description = "extracts information from sms-freiburg.de and shares it via MQTT"
authors = [
    {name = "Gabi Röger"},
]
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "GPL-3.0-only"

dependencies = [
  "paho-mqtt==2.1.0",
  "PyYAML==6.0.3",
  "selene==2.0.0rc10",
  "selenium==4.50.0"
]

[project.urls]
Issues = "https://github.com/roeger/sms-freiburg/issues"
Repository = "https://github.com/roeger/sms-freiburg"

[tool.setuptools.dynamic]
version = {file = "VERSION"}

[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
